proxies:
- name: å°æ¹¾Akile
  dialer-proxy: AutoTW ğŸ‡¨ğŸ‡³
  type: ss
  server: akilehinetnat.645781.xyz
  port: 10490
  cipher: aes-128-gcm
  password: db756bc3-09ef-4550-82e0-d3c4395e8348
  udp: true
